### ISSUE TITLE
Can't compile on ubuntu 21.04

### ISSUE THREAD

**Issue by hellisabove** [OothecaPickle/xpwn#12]
/usr/bin/ld: libxpwn.a(libxpwn.c.o):(.bss+0x0): multiple definition of `endianness'; CMakeFiles/ipsw.dir/main.c.o:(.bss+0x8): first defined here
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [ipsw-patch/CMakeFiles/ipsw.dir/build.make:115: ipsw-patch/ipsw] Error 1
make[1]: *** [CMakeFiles/Makefile2:557: ipsw-patch/CMakeFiles/ipsw.dir/all] Error 2
make: *** [Makefile:171: all] Error 2

**Comment by Merculous** [comment]
I also have this issue on Ubuntu 22.04 LTS, how did you fix this error, if you indeed did?

**Comment by Merculous** [comment]
I figured it out, according to the research I've done, CFLAG -fno-common is what makes this issue appear. To fix it just export CFLAGS and enter -fcommon.
